import api from './api';
import BigNumber from "bignumber.js";
type PosData = any;
const formatId = (id: string | number): string => {
    return new BigNumber(id).toFixed();
};
export const addToCart =  async (data: PosData) => api.post('/api/order/add-to-cart', data);
export const checkout = async (id : string) => api.post(`/api/order/checkout?orderId=${formatId(id)}`);
export const getPromoCodes = async () => api.get('/api/promotion');
export const validatePromoCode = async (orderId: string, code: string) =>  api.patch(`/api/order/${formatId(orderId)}/apply-promotion`, { codePromotion: code });
export const minusQuantity = async (id: string ) => api.patch(`/api/order/minus-quantity?productId=${formatId(id)}`);
export const plusQuantity = async (id: string ) => api.patch(`/api/order/add-quantity?productId=${formatId(id)}`);
export const deleteFromCart = async (id: string ) => api.delete(`/api/order/delete-from-cart?productId=${formatId(id)}`);
export const usePromoCode = async (orderId: string) =>  api.get(`/api/order/${formatId(orderId)}/use-promotion`);
export const searchProduct = async (query: string) => api.get(`/api/search?query=${query}`);
export const getPromoCodesById = async (id: string) => api.get(`/api/promotion/${formatId(id)}`);
export const deletePromoCode = async (id: string) => api.delete(`/api/promotion/${formatId(id)}`);
export const createPromoCode = async (data: any) => api.post('/api/promotion', data);
export const updatePromoCode = async (id: string, data: any) => api.patch(`/api/promotion/${formatId(id)}`, data);
export const getOrders = async () => api.get('/api/order');
export const getOrderById = async (id: string) => api.get(`/api/order/${formatId(id)}`);
export const deleteOrderById = async (id: string) => api.delete(`/api/order/${formatId(id)}`);